name = "Gijsemans and Friends"
author = "Onoref, woutwoot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4476fbedadf3f79002af9bac924bfe933603edd061fa5cd031226e0751a9aeb"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
