name = "Gijsemans and Friends"
author = "Onoref, woutwoot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce430794c568951d908df793f38f53adfa9e9b251aa8263d466b0c1ac47daa10"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
